### ISSUE TITLE
remove remnants of Form Builder

### ISSUE THREAD

**Issue by lmkw** [NUARIG/competitions#217]
increase test coverage for Form Builder

- [x] GrantSubmission::Form closed in #210
- [x] GrantSubmission::Section closed in #220
- [x] GrantSubmission::Response closed in #226 
- [x] GrantSubmission::Submission closed in #226
- [x] GrantSubmission::MultipleChoiceOption closed in #226 

More cleanup will likely be needed. Will open additional tickets as needed.

**Comment by jseraf** [comment]
GrantSubmission::Form closed in #210 
GrantSubmission::Section closed in #220

**Comment by jseraf** [comment]
GrantSubmission::Question in progress

**Comment by jseraf** [comment]
GrantSubmission::Question and GrantSubmission::MultipleChoiceOption closed in #226

**Comment by jseraf** [comment]
GrantSubmission::Response, ::Submission, ::MultipleChoiceOption closed in #230
