### ISSUE TITLE
Testing 0.9.8 release branch

### ISSUE THREAD

**Issue by jseraf** [NUARIG/competitions#448]
Testing should include:

- [x] Grant New functionality (#381)
- [x] Grant Duplicate functionality (#381)
- [x] Review of proper scoring Submission's average Overall Impact Score (#419, #439)
- [x] Sorting on Submissions by Overall Impact Score (#419, #431 )
- [x] Review of proper scoring Submission's Composite (#419, #439)
- [x] Sorting on Submissions by Overall Impact Score (#419, #431)
- [x] Front end updates (#441, #454)

**Comment by jseraf** [comment]
Pending #447

**Comment by lmkw** [comment]
Questions:
When someone creates a grant and finishes the overview, why do we deposit them on the Permissions tab?

**Comment by jseraf** [comment]
@lmkw that section was most likely the first one built out after grants.
