### ISSUE TITLE
Test 0.9.9 branch

### ISSUE THREAD

**Issue by jseraf** [NUARIG/competitions#482]
Test on alpha with existing Competitions (submissions/reviews) and new test Grants as admin
Test on staging for new Submission/Reviews as applicant

See tickets below for specific updates:
- [x] Banner form #470 
- [x] Banner flash notices (visible vs not visible) #469 
- [x] Front end updates
  - [x] Grant Duplicate landing page #453 
  - [x] Update Submission Reviews header #463 
  - [x] Line breaks in review comments #464 
  - [x] Guidance on Questions page #451
  - [x] Typos and broken link on Review Criteria page #454 
  - [x] Print Stylesheet #450 
- [x] PDF Export from Submissions tab #460
- [x] Excel Export from Reviews index #459
- [x] Fix calculated scores for existing reviewed submissions #473

**Comment by jseraf** [comment]
@lmkw #495 and #453 have been updated and deployed to the cd2h staging server.

**Comment by lmkw** [comment]
All looks well with regard to the two reopened tickets, #453 and #459
