### ISSUE TITLE
Requirements gathering for tracking and notifying award winners

### ISSUE THREAD

**Issue by lmkw** [NUARIG/competitions#824]
Related to #263 
How does the information get stored? Is this a new attribute on the Submission table or a new Awardee table that's a join between Submission and Grant

- Needs to be able to track potentially multiple winners and notify winners and non-winners 
- What information do you want to include in the mailer? Where is that information stored?
- Do we want to track amount awarded? Distributed among multiple awardees?

Ideas to run by Keith and others, separate issues under this feature:

Do we want to show that a grant was awarded? Create show page for closed grants?
Are winners names/application titles publicly viewable? Is it okay to list winners for all competitions or should it be configurable per competition?

**Comment by mattbaumann1** [comment]
Met with @jseraf today and discussed the design. Below is what we decided for the course of action. 

- [ ] Consult with Yulia about StudyBudget comparisons
- [ ] Add column to submissions for award amount
- [ ] Add column to grants for maximum awarded amount. (Should this be required?)
- [ ] Error handling for calculations between the two columns if not required.
- [ ] Awardable validations (must be reviewed and submitted before awarded)
- [ ] Add a new column on the submission index page. The heading has the maximum amount awarded and the rows have amount awarded.
- [ ] Link to open a modal to add amount awarded to a submission.

Notifications will be handled separately.

**Comment by mattbaumann1** [comment]
Notes from meeting with Keith, June 18,2021

Submissions
  - columns to add
    - amount awarded (number field)
  - validations
    - must be reviewed before they are awarded
    - must be in submitted state, not draft

Grants
  - columns to add
    - maximum awarded amount (not required)
    - upper bound an applicant can ask for (maybe)
    - award begin and end dates
  - calculations that show amount remaining to be awarded
    - this will need error handling if maximum awarded amount is not required.

UI
  - grant/id/submissions index
    - add column for awards
      - heading has maximum
      - rows have amount awarded or link to add amount
        - link opens modal to enter amount (reloads table)
  - add new menu item for award notifications to grants
    - this page should have 
      - checkboxes for awarded and not awarded (waitlist?)
      - button to send each type of notification in batch
      - maybe put the awarded amount on this page instead of on submissions index?
  - review page
    - add prompt for reviewers that applicants will see comments if grant admin checks this.

Notifications
  - types
    - awardees
    - rejection letters
    - waitlist?
  - requirements
    - pipe in submission title and applicant names
    - show unique number of awarded amount
    - award begin and end dates
    - can be set text
      - maybe in future add ability to customize
    - reviewer comments
      - anonymous? (probably yes)
      - scores? (probably not)
      - could be pdf, link to application, or in email.
  - validations
    - should be after panel? if panel 
      - is this needed to use the system? (EDW?)

Excel export
  - submissions
    - add amount awarded

Future work
  - add notification to touch base during award
    - remind them to spend the money
    - time remaining
  - report mechanism for end of funding period
    - publication list
    - downstream grants supported
    - prose description of what they accomplished

FUTURE REQUIREMENTS GATHERING
  - ask Emily what is needed for the Ks and Ts
    -especially ask about requirements for a notification system

**Comment by mattbaumann1** [comment]
Notes from meeting with Dan Schneider on June 24, 2021

The EDW have a rolling competition where awardees are determined as the applications come in and they will either be accepted or rejected. Each submission is judged against itself, not against other submissions. 

Submissions
  - Requirements
    - Needs to show accepted/awardees and rejected
    - Needs to sort on awarded and rejected
    - Needs a way to hide submissions awarded/rejected.

Grants
  - Requirements
    - No need to count down from available amount.
    - Might not know the total amount available at the time of the grant creation.
    - There is a cap of 12 hours per IRB Numbers.

UI
  Requirements
    - Awardees should not be public

Notifications
  - Types
    - Awardees
    - Rejections
    - No waitlist
  - Requirements
    - Should automate notification of applicant
    - Applicant should see reviewers comments and scores
    - should be able to CC people
      - Could just be grant permissions for now

  - Email text
    - prefer custom text for email.
    - Examples below

Acceptance
Hello <APPLICANT NAME>,
 
Your recent <GRANT TITLE> submission titled “<SUBMISSION TITLE>,” has been accepted!
 
The support team will create a ticket in our intake form and this should be assigned to an analyst in the next few days. This awards you 12 hours of analyst time for your project. For support, please see below for details we will need to add to the intake ticket.
 
Thank you,
 
<GRANT ADMIN>
 
--
 
Rejection
Hello <APPLICANT NAME>,
 
Your recent <GRANT TITLE> submission titled “<SUBMISSION TITLE>,” has not been accepted.
 
It failed to meet our definition of Prep to Research. If you would like to explain further how this request is prep to research please respond here.
 
Thank you,
 
<GRANT ADMIN>

**Comment by lmkw** [comment]
**Home page of Competitions**
_Do you want to show that a grant was awarded (on the home page of Competitions)?_ Sure
 
_Do you want an area on Competitions for closed grants?_ Yes – I want to be able to see past applications with related documents/applicants

_Are winners names/application titles publicly viewable? Is it okay to list winners for all competitions or should it be configurable per competition?_ Winners are public, I’d just want to be sure that we didn’t put in dispositions on applicants until we have everything squared away with those who are going to be appointed and those who were not appointed hear from us directly before seeing it in the portal.
 
**Admin views of Competitions**
 
**Overview**
_On the Overview tab we’ll have fields for maximum awarded amount, upper limit that an applicant can ask for, award begin and end dates_

**Submissions tab**
_We’re thinking of adding an “Amount Awarded” column to the Submissions tab (number field)
Submissions must be reviewed before they are awarded, must be in submitted state not draft
A link will open a pop-up to enter amounts
As grants are awarded we can show the remaining amount to be awarded_
 
**Notifications tab?**
 
_Will add a new menu item for award notifications to submitters/applicants
This page should have checkboxes for awarded and not awarded
Buttons to send each type of notification
Maybe put the awarded amount on this page instead of on Submissions tab? This is fine_
 
Do you have a need for putting people on a waitlist?  I don’t think we would use this feature in competitions, sometimes we have to finagle the list a bit as we are working through appointments/negotiating other awarded grants, and I don’t think having a waitlist in this portal would be helpful for us.
Do you need custom text for awarded and not-awarded emails? Or is it okay to have a template with submission title, awarded amount, award begin and end dates For our purposes, because of the nature of the award, we send individualized, tailored emails to applicants from our PI/program admin. We won’t use the portal to send emails.
Do you (want to) send reviewer comments to awardees/non-awardees?  Anonymously (I assume)? Scores? No. Again, because of the nature of the award we sometimes end up editing the reviewer comments so they land a little easier. Not always, but we at least need to have the option to tailor what goes on to the applicants while still maintaining a record of actual reviewer comments.
Should amounts awarded be part of the Excel export of Submissions? Sure. My preference is to have all data captured in the system exportable and then we can filter out what we don’t use.
